<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="FYProject.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <p> An email that contains short description, aim and purpose of the study, with a link to the online questionnaire, was sent out to Year 1 CMS students by the supervisor of this course. The results were a little bit disappointing at first, because only 31 students entered their answers to the questionnaire. Nevertheless, the summary of responses by the students were quite enough to prove the feasibility of this study.</p>
    <p> The results show that 61.3% of the students identified themselves as ‘Beginners’ in programming, also with 19.4% and 6.5% respectively as ‘Intermediate’ and ‘Advanced’ programmers. Only 4 students (12.9%) were identified as ‘No knowledge’ (no previous experience). As the aim of the final product is to motivate mainly beginners, the study acquired good results.</p>
    <p> When asked ‘Which Programming languages do you know already?’ responses show that most of the students (72.4%) are already familiar with ‘Java’. This is due to the fact that most of the First Year students are enrolled on computer programming courses with ‘Java’. A third of them (37.9%) also familiar with ‘C#’, a knowledge and experience more likely gained through college or self-study. As these two languages are the most common among students, the rest of the answers will be ignored. Ignored because students shared that they would like to practice and learn ‘C#’ the most (51.6%), followed by ‘Java’ (29%). </p>
    <p> Most of the students (25.8%) were not confident and sure with their programming skills, which reveals a serious problem. Hopefully the end product will be able to motivate them in their studies. To mention, a reason for motivation to the author of this project, was the positive answers of the students who mostly liked the idea of the project. This means that they believe in the success of this project.</p>
    <p> Another area to note is students approach positively the idea of using interactive learning environment with games (87.1%) answering with ‘Yes’ and small quizzes (48.4%). They believe that this approach will help them to get motivated in programming. </p>
    <p> To conclude due to tight deadlines only one language will be available to practice at this point, which is ‘C#’, the champion with 51.6%. Moreover more emphasis will be on implementing simple games to grab the attention of the students and if time permits some quizzes will be added as well. Future improvements to the learning environment could be the added in feature to practice more than one language (e.g. C#, Java, JavaScript and etc.) and availability of more interactive content not limited to only one or two.</p>
    <p> Please check the questionnaire and summary of responses available at Appendix B of the report. </p>
</asp:Content>
